# Dependencies
markdown:         redcarpet
highlighter:      pigments

# Permalinks
permalink:        pretty

# Setup
title:            Hyperspark
tagline:          'Distributed meta-heuristics on top of Spark'
description:      'A framework for running meta-heuristic algorithms on a cluster of commodity computers.<br>Developed at <a href="http://www.deib.polimi.it/eng/home-page">DEIB</a> in Politecnico di Milano by <a href="https://github.com/nemtajo">Nemanja Stolic</a>'
url:              http://deib-polimi.github.io/hyperspark

authors:
  nemanja:
    name:           'Nemanja Stolic'
    url:            https://github.com/nemtajo
  camilo:
    name:           'Camilo Martinez'
    url:            https://github.com/camilomartinez

paginate:         1
paginate_path:    "/blog/page:num/"

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/deib-polimi/hyperspark
